### ISSUE TITLE
Image reader reading version number incorrectly?

### ISSUE THREAD

**Issue by franklinwk** [SlicerIGT/MatlabOpenIGTLink#5]
When running the function in matlab with image data being received via OpenIGTLink from 3D Slicer, the version number is being read as 0 instead of 1 and the rest of the image data ends up being read incorrectly as well. I believe the version number occupies 2 bytes rather than 1 byte.

function [name data] = handleImageMessage(msg, onRxStringMessage)
    body = msg.body;
    i=1;

```
versionNumber = uint8(body(i)); i = i + 1;
```

**Comment by lassoan** [comment]
Thanks a lot for the information. It would be great if you could send a pull request with the fix.
